apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  namespace: default
  labels:
    app: demo-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-nginx
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      initContainers:
      - name: move-html
        image: busybox
        command:
          - "sh"
          - "-c"
          - |
            if [ -d /git/argocd/manifests/html ] && [ "$(ls -A /git/argocd/manifests/html)" ]; then
              cp -r /git/argocd/manifests/html/* /usr/share/nginx/html/
            else
              echo 'No files to copy'
            fi
        volumeMounts:
        - name: git-volume
          mountPath: /git
        - name: html-volume
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.4.0
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/jhunter7/argocd.git"  # Replace with your GitHub repo URL
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: "/git"
        - name: GIT_SYNC_WAIT
          value: "30"  # Poll every 30 seconds for changes
        volumeMounts:
        - name: git-volume
          mountPath: /git
      volumes:
      - name: git-volume
        emptyDir: {}
      - name: html-volume
        emptyDir: {}

